[package]
name = "editor"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
client.workspace = true
game_core.workspace = true
glam.workspace = true
map_forge.workspace = true
renderer_api.workspace = true
renderer_wgpu.workspace = true
scene_build.workspace = true
terrain.workspace = true
winit.workspace = true

[dev-dependencies]
png = "0.18"

[lints]
workspace = true
