[package]
name = "sdf_mesh"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
glam.workspace = true
png.workspace = true
sdf.workspace = true
vehicle_geometry.workspace = true

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "meshing"
harness = false

[lints]
workspace = true
