[package]
name = "vehicle_build"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
cast_loft.workspace = true
detail.workspace = true
game_core.workspace = true
glam.workspace = true
panel.workspace = true
revolve.workspace = true
sdf.workspace = true
sdf_mesh.workspace = true
solid.workspace = true
sweep.workspace = true
thiserror.workspace = true
vehicle_geometry.workspace = true

[lints]
workspace = true
