//! The garage screen's element names (interface program F5, G1–G7): every plate, word, icon
//! and control of the hangar screen by name on the draw list; the tree's legacy vertices ride
//! `TechTree` until G12. Append-only.

/// Append-only. The first ten were the F5 panels carried as legacy vertices; the hangar's
/// panels are elements of their own now, the tree still rides `TechTree` and `Hover`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub(crate) enum GarageElement {
    TopBar,
    Nameplate,
    Crew,
    Stats,
    Loadout,
    Carousel,
    InspectorLegend,
    Options,
    TechTree,
    /// The legacy wash over a tree node or its BACK.
    Hover,
    TopBarRule,
    BattleButton,
    BattleLabel,
    MapRow,
    MapLabel,
    TabGarage,
    TabTechTree,
    NamePlate,
    NameText,
    NameLine,
    NameRole,
    NameTag,
    LegendPlate,
    LegendTitle,
    LegendSwatch(u8),
    LegendLabel(u8),
    LegendUnit,
    CrewPlate,
    CrewHeader,
    CrewRule,
    CrewIcon(u8),
    CrewRole(u8),
    StatsPlate,
    StatsHeader,
    StatsRule,
    StatsTier,
    StatIcon(u8),
    StatLabel(u8),
    StatValue(u8),
    StatBar(u8),
    StatTick(u8),
    LoadoutPlate,
    ModuleSlot(u8),
    ModuleIcon(u8),
    ModuleSummary(u8),
    AmmoSlot(u8),
    AmmoIcon(u8),
    AmmoName(u8),
    AmmoFigures(u8),
    AmmoCount(u8),
    AmmoMinus(u8),
    AmmoPlus(u8),
    RackTotal,
    CarouselPlate,
    CarouselCell(u8),
    CarouselNation(u8),
    CarouselName(u8),
    SilhouetteHull(u8),
    SilhouetteTurret(u8),
    SilhouetteBarrel(u8),
    CarouselArrow(u8),
    CarouselArrowGlyph(u8),
    OptionsPlate,
    OptionsHeader,
    OptionRow(u8),
    OptionName(u8),
    OptionStat(u8),
    OptionDelta(u8),
}

impl GarageElement {
    /// Walked by the tests; the identity rule wants it whole (a data variant once).
    #[cfg_attr(not(test), allow(dead_code))]
    pub const ALL: [GarageElement; 68] = [
        GarageElement::TopBar,
        GarageElement::Nameplate,
        GarageElement::Crew,
        GarageElement::Stats,
        GarageElement::Loadout,
        GarageElement::Carousel,
        GarageElement::InspectorLegend,
        GarageElement::Options,
        GarageElement::TechTree,
        GarageElement::Hover,
        GarageElement::TopBarRule,
        GarageElement::BattleButton,
        GarageElement::BattleLabel,
        GarageElement::MapRow,
        GarageElement::MapLabel,
        GarageElement::TabGarage,
        GarageElement::TabTechTree,
        GarageElement::NamePlate,
        GarageElement::NameText,
        GarageElement::NameLine,
        GarageElement::NameRole,
        GarageElement::NameTag,
        GarageElement::LegendPlate,
        GarageElement::LegendTitle,
        GarageElement::LegendSwatch(0),
        GarageElement::LegendLabel(0),
        GarageElement::LegendUnit,
        GarageElement::CrewPlate,
        GarageElement::CrewHeader,
        GarageElement::CrewRule,
        GarageElement::CrewIcon(0),
        GarageElement::CrewRole(0),
        GarageElement::StatsPlate,
        GarageElement::StatsHeader,
        GarageElement::StatsRule,
        GarageElement::StatsTier,
        GarageElement::StatIcon(0),
        GarageElement::StatLabel(0),
        GarageElement::StatValue(0),
        GarageElement::StatBar(0),
        GarageElement::StatTick(0),
        GarageElement::LoadoutPlate,
        GarageElement::ModuleSlot(0),
        GarageElement::ModuleIcon(0),
        GarageElement::ModuleSummary(0),
        GarageElement::AmmoSlot(0),
        GarageElement::AmmoIcon(0),
        GarageElement::AmmoName(0),
        GarageElement::AmmoFigures(0),
        GarageElement::AmmoCount(0),
        GarageElement::AmmoMinus(0),
        GarageElement::AmmoPlus(0),
        GarageElement::RackTotal,
        GarageElement::CarouselPlate,
        GarageElement::CarouselCell(0),
        GarageElement::CarouselNation(0),
        GarageElement::CarouselName(0),
        GarageElement::SilhouetteHull(0),
        GarageElement::SilhouetteTurret(0),
        GarageElement::SilhouetteBarrel(0),
        GarageElement::CarouselArrow(0),
        GarageElement::CarouselArrowGlyph(0),
        GarageElement::OptionsPlate,
        GarageElement::OptionsHeader,
        GarageElement::OptionRow(0),
        GarageElement::OptionName(0),
        GarageElement::OptionStat(0),
        GarageElement::OptionDelta(0),
    ];
}

#[cfg(test)]
mod tests {
    use super::GarageElement;

    #[test]
    fn every_element_is_named_once() {
        let names: std::collections::HashSet<String> =
            GarageElement::ALL.iter().map(|e| format!("{e:?}")).collect();
        assert_eq!(names.len(), GarageElement::ALL.len());
    }
}
