//! The garage screen's element names (interface program F5, G1–G7): every plate, word, icon
//! and control of the hangar screen by name on the draw list; the tree's legacy vertices ride
//! `TechTree` until G12. Append-only.

/// Append-only. The first ten were the F5 panels carried as legacy vertices; the hangar's
/// panels are elements of their own now, the tree still rides `TechTree` and `Hover`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub(crate) enum GarageElement {
    TopBar,
    Nameplate,
    Crew,
    Stats,
    Loadout,
    Carousel,
    InspectorLegend,
    Options,
    TechTree,
    /// The legacy wash over a tree node or its BACK.
    Hover,
    TopBarRule,
    BattleButton,
    BattleLabel,
    MapRow,
    MapLabel,
    TabGarage,
    TabTechTree,
    NamePlate,
    NameText,
    NameLine,
    NameRole,
    NameTag,
    LegendPlate,
    LegendTitle,
    LegendSwatch(u8),
    LegendLabel(u8),
    LegendUnit,
    CrewPlate,
    CrewHeader,
    CrewRule,
    CrewIcon(u8),
    CrewRole(u8),
    StatsPlate,
    StatsHeader,
    StatsRule,
    StatsTier,
    StatIcon(u8),
    StatLabel(u8),
    StatValue(u8),
    StatBar(u8),
    StatTick(u8),
    LoadoutPlate,
    ModuleSlot(u8),
    ModuleIcon(u8),
    ModuleSummary(u8),
    AmmoSlot(u8),
    AmmoIcon(u8),
    AmmoName(u8),
    AmmoFigures(u8),
    AmmoCount(u8),
    AmmoMinus(u8),
    AmmoPlus(u8),
    RackTotal,
    CarouselPlate,
    CarouselCell(u8),
    CarouselNation(u8),
    CarouselName(u8),
    SilhouetteHull(u8),
    SilhouetteTurret(u8),
    SilhouetteBarrel(u8),
    CarouselArrow(u8),
    CarouselArrowGlyph(u8),
    OptionsPlate,
    OptionsHeader,
    OptionRow(u8),
    OptionName(u8),
    OptionStat(u8),
    OptionDelta(u8),
    /// The key legend on the top bar (G6), one line each.
    HintLine(u8),
    /// The carousel's filter chips (G9): the control, its label, its value.
    Chip(u8),
    ChipLabel(u8),
    ChipValue(u8),
    /// The tooltip of the control the cursor rests on (G6).
    TooltipPlate,
    TooltipText,
    /// The compared hull's name on the VEHICLE column's header (G3), and its numbers and the
    /// signed deltas beside the own column.
    CompareName,
    StatOther(u8),
    StatDelta(u8),
    /// The five tabs the bar grew (G10); GARAGE and TECH TREE are above.
    TabArmour,
    TabBattles,
    TabReplays,
    TabStatistics,
    TabSettings,
    /// The tech tree on the list (G12): the panel, the key, a line's head, the nodes by
    /// absolute roster index, the edge from a node to what follows it, BACK.
    TreePanel,
    TreeLinesLabel,
    TreeTierLabel(u8),
    TreeLineIcon(u8),
    TreeLineLabel(u8),
    TreeNode(u8),
    TreeNodeIcon(u8),
    TreeNodeName(u8),
    TreeNodeTier(u8),
    TreeNodeNext(u8),
    TreeEdge(u8),
    TreeBack,
    TreeBackLabel,
    /// The inspector's readout under the legend (G11): the plate's line, the verdict's line,
    /// the SHOOT ME switch.
    InspectorPlate,
    InspectorLine(u8),
    InspectorShootMe,
    InspectorShootMeLabel,
    /// The nation's colour at a tree line's head (the look pass): a swatch, not the words.
    TreeLineSwatch(u8),
}

impl GarageElement {
    /// A tab's element (G10).
    pub fn tab(tab: super::types::GarageTab) -> Self {
        use super::types::GarageTab;
        match tab {
            GarageTab::Garage => GarageElement::TabGarage,
            GarageTab::TechTree => GarageElement::TabTechTree,
            GarageTab::Armour => GarageElement::TabArmour,
            GarageTab::Battles => GarageElement::TabBattles,
            GarageTab::Replays => GarageElement::TabReplays,
            GarageTab::Statistics => GarageElement::TabStatistics,
            GarageTab::Settings => GarageElement::TabSettings,
        }
    }
}

impl GarageElement {
    /// Walked by the tests; the identity rule wants it whole (a data variant once).
    #[cfg_attr(not(test), allow(dead_code))]
    pub const ALL: [GarageElement; 100] = [
        GarageElement::TopBar,
        GarageElement::Nameplate,
        GarageElement::Crew,
        GarageElement::Stats,
        GarageElement::Loadout,
        GarageElement::Carousel,
        GarageElement::InspectorLegend,
        GarageElement::Options,
        GarageElement::TechTree,
        GarageElement::Hover,
        GarageElement::TopBarRule,
        GarageElement::BattleButton,
        GarageElement::BattleLabel,
        GarageElement::MapRow,
        GarageElement::MapLabel,
        GarageElement::TabGarage,
        GarageElement::TabTechTree,
        GarageElement::NamePlate,
        GarageElement::NameText,
        GarageElement::NameLine,
        GarageElement::NameRole,
        GarageElement::NameTag,
        GarageElement::LegendPlate,
        GarageElement::LegendTitle,
        GarageElement::LegendSwatch(0),
        GarageElement::LegendLabel(0),
        GarageElement::LegendUnit,
        GarageElement::CrewPlate,
        GarageElement::CrewHeader,
        GarageElement::CrewRule,
        GarageElement::CrewIcon(0),
        GarageElement::CrewRole(0),
        GarageElement::StatsPlate,
        GarageElement::StatsHeader,
        GarageElement::StatsRule,
        GarageElement::StatsTier,
        GarageElement::StatIcon(0),
        GarageElement::StatLabel(0),
        GarageElement::StatValue(0),
        GarageElement::StatBar(0),
        GarageElement::StatTick(0),
        GarageElement::LoadoutPlate,
        GarageElement::ModuleSlot(0),
        GarageElement::ModuleIcon(0),
        GarageElement::ModuleSummary(0),
        GarageElement::AmmoSlot(0),
        GarageElement::AmmoIcon(0),
        GarageElement::AmmoName(0),
        GarageElement::AmmoFigures(0),
        GarageElement::AmmoCount(0),
        GarageElement::AmmoMinus(0),
        GarageElement::AmmoPlus(0),
        GarageElement::RackTotal,
        GarageElement::CarouselPlate,
        GarageElement::CarouselCell(0),
        GarageElement::CarouselNation(0),
        GarageElement::CarouselName(0),
        GarageElement::SilhouetteHull(0),
        GarageElement::SilhouetteTurret(0),
        GarageElement::SilhouetteBarrel(0),
        GarageElement::CarouselArrow(0),
        GarageElement::CarouselArrowGlyph(0),
        GarageElement::OptionsPlate,
        GarageElement::OptionsHeader,
        GarageElement::OptionRow(0),
        GarageElement::OptionName(0),
        GarageElement::OptionStat(0),
        GarageElement::OptionDelta(0),
        GarageElement::HintLine(0),
        GarageElement::Chip(0),
        GarageElement::ChipLabel(0),
        GarageElement::ChipValue(0),
        GarageElement::TooltipPlate,
        GarageElement::TooltipText,
        GarageElement::CompareName,
        GarageElement::StatOther(0),
        GarageElement::StatDelta(0),
        GarageElement::TabArmour,
        GarageElement::TabBattles,
        GarageElement::TabReplays,
        GarageElement::TabStatistics,
        GarageElement::TabSettings,
        GarageElement::TreePanel,
        GarageElement::TreeLinesLabel,
        GarageElement::TreeTierLabel(0),
        GarageElement::TreeLineIcon(0),
        GarageElement::TreeLineLabel(0),
        GarageElement::TreeNode(0),
        GarageElement::TreeNodeIcon(0),
        GarageElement::TreeNodeName(0),
        GarageElement::TreeNodeTier(0),
        GarageElement::TreeNodeNext(0),
        GarageElement::TreeEdge(0),
        GarageElement::TreeBack,
        GarageElement::TreeBackLabel,
        GarageElement::InspectorPlate,
        GarageElement::InspectorLine(0),
        GarageElement::InspectorShootMe,
        GarageElement::InspectorShootMeLabel,
        GarageElement::TreeLineSwatch(0),
    ];
}

#[cfg(test)]
mod tests {
    use super::GarageElement;

    #[test]
    fn every_element_is_named_once() {
        let names: std::collections::HashSet<String> =
            GarageElement::ALL.iter().map(|e| format!("{e:?}")).collect();
        assert_eq!(names.len(), GarageElement::ALL.len());
    }
}
