[package]
name = "scene_build"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
game_core.workspace = true
glam.workspace = true
map_forge.workspace = true
png.workspace = true
serde_json.workspace = true
renderer_api.workspace = true
terrain.workspace = true
world_forge.workspace = true

[lints]
workspace = true

[dev-dependencies]
sim.workspace = true
