[package]
name = "client"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
ui_kit.workspace = true
anyhow.workspace = true
audio.workspace = true
battle_host.workspace = true
cpal.workspace = true
deform.workspace = true
engine.workspace = true
game_core.workspace = true
map_forge.workspace = true
glam.workspace = true
net.workspace = true
physics.workspace = true
png.workspace = true
renderer_api.workspace = true
scene_build.workspace = true
timer_resolution.workspace = true
chrono.workspace = true
renderer_wgpu.workspace = true
serde.workspace = true
serde_json.workspace = true
sim.workspace = true
terrain.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
vehicle_forge.workspace = true
vehicle_recipes.workspace = true
world_forge.workspace = true
vehicle_geometry.workspace = true
winit.workspace = true

[lints]
workspace = true
