[package]
name = "client"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
ab_glyph = "0.2"
anyhow.workspace = true
audio.workspace = true
cpal.workspace = true
deform.workspace = true
engine.workspace = true
game_core.workspace = true
glam.workspace = true
net.workspace = true
physics.workspace = true
png = "0.18"
renderer_api.workspace = true
renderer_wgpu.workspace = true
serde.workspace = true
serde_json.workspace = true
server.workspace = true
sim.workspace = true
terrain.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
vehicle_forge.workspace = true
vehicle_geometry.workspace = true
winit.workspace = true

[dev-dependencies]
png = "0.18"
vehicle_build.workspace = true

[lints]
workspace = true
