[package]
name = "vehicle_forge"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
game_core = { path = "../game_core" }
glam.workspace = true
png = "0.18"
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
vehicle_build = { path = "../vehicle_build" }
vehicle_geometry = { path = "../vehicle_geometry" }

[lints]
workspace = true
