[package]
name = "vehicle_forge"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
game_core = { path = "../game_core" }
glam.workspace = true
serde.workspace = true
thiserror.workspace = true
vehicle_geometry = { path = "../vehicle_geometry" }

[lints]
workspace = true
